### ISSUE TITLE
support for asynchronous actions

### ISSUE THREAD

**Issue by amit1911** [socialtables/redux-unhandled-action#4]
i keep getting the following error for async actions

```
action with type undefined did not modify the data in any reducer.You may have mutated state directly or you may have a typo in your reducer
```

i think this is because of the following code in the middleware.

```
const prevState = getState();
const result = next(action);
const nextState = getState();
```

Since the action here is a function which returns a promise we need to compare the `nextState` with the `prevState` only after the promise has been resolved. Something like the following might fix the issue

```
const prevState = getState();
const result = Promise.resolve(next(action));
result.then(() => {
    const nextState = getState();
    if (prevState === nextState) {
        callback(action);
    }
});

return result;
```

The above issue will only happen if thunk middleware is added after the redux-unhandled-action middleware. Something like the following

```
applyMiddleware(reduxUnhandledAction(), thunk)
```

But if we add thunk at the beginning, then this issue will not happen as the async action will not be forwarded to the other middlewares. So the following will work fine

```
applyMiddleware(thunk, reduxUnhandledAction())
```

So I am not sure if there is need to fix it. If this is the expected behavior, then the issue can be closed.

**Comment by conorhastings** [comment]
@amit1911 you're exactly right at the end of the comment, it needs to be placed at the end of the middleware chain. Would you like to make a pr making that more clear in the README! That would be super helpful

**Comment by amit1911** [comment]
@conorhastings shouldn't we make the middleware support these type of actions? That way it doesn't have to be added after the 'thunk' middleware.

**Comment by conorhastings** [comment]
@amit1911 If we're going to make it position agnostic, I think we should just ignore actions that are not plain objects instead of resolving them, since the middleware can take on unknowable types, would accept a PR for that as well.

**Comment by amit1911** [comment]
@conorhastings yeah i agree. We can just handle actions that are plain objects and have a valid 'type' property since that is what the redux dispatcher method does. 
Original Code from redux dispatcher

```
if (!isPlainObject(action)) {
    throw new Error(
        'Actions must be plain objects. ' +
        'Use custom middleware for async actions.'
    )
}

if (typeof action.type === 'undefined') {
    throw new Error(
        'Actions may not have an undefined "type" property. ' +
        'Have you misspelled a constant?'
    )
}
```

Since we do not need to throw errors for invalid actions as they can be processed by other middlewares, for our case we just need to ignore them so we can have something like the following

```
if (isPlainObject(action)) {
    if (typeof action.type !== 'undefined') {
        // our middleware processing
    }
}
return next(action);
```

If you are okay with this, then I'll create a PR soon.

**Comment by conorhastings** [comment]
@amit1911 👍 that sounds great!

**Comment by amit1911** [comment]
created the pull request (#6) as discussed. apologies for the delay.
Moreover, I also found 1 minor bug in the tests but did not fix it in this pull request as it's not related to this pull request so wasn't sure if I should fix it in this pull request.
The issue is in the 5th test case

```
test("should not error when state is properly updated", function(assert) {
    var action = {
        type: "COOL_ACTION"
    };
    var consoleError = sinon.stub(console, "error");
    var actionHandler = unhandledAction()({getState: getState})(next)(action);
    assert.notOk(consoleError.called, "console error is not logged when a new state is returned");
    assert.end();
});
```

The above test case is stubbing the `error` function of `console` object but it is not restoring the original functionality at the end. So we should call `consoleError.restore()` in the end, otherwise it will throw error if we try to stub it again in any of the following test cases.

**Comment by conorhastings** [comment]
@amit1911  thanks! fixed the console.error thing here https://github.com/socialtables/redux-unhandled-action/commit/e63f47ad6a80a75b656f177ecd90cc2982aee0ba , and published your change as `1.2.0`. Thanks so much again for submitting the PR!

**Comment by oyeanuj** [comment]
@conorhastings @amit1911 So, is the middleware position agnostic? Or does it come at the end?

**Comment by conorhastings** [comment]
@oyeanuj should be position agnostic now
